### ISSUE TITLE
Implicit behavior of the plugin on overriding already defined properties

### ISSUE THREAD

**Issue by temalead** [Mikhail2048/properties-maven-plugin#4] opened 2023-05-09 19:00 UTC
Description of [PropertiesLoader](https://github.com/Mikhail2048/properties-maven-plugin/blob/master/src/main/java/io/polivakha/mojo/properties/loader/PropertiesLoader.java) mentioned that:
_if there is a property 'abc' defined in 
3 resources, then the value of 'abc' property in the last resource in the passed list will be contained
in the returned {@link Properties} object._
     
I think it`s implicit behaviour of plugin. What if in one of the propertiy files property value was updated to actual value, for example db datasource, but plugin reads deprecated value from other file

Maybe we can throw exception if property already is defined in one of the files?

**Comment by mipo256** [comment] 2023-05-10 08:30
I do not think I fully understand your point.

This problem you described seems to have a pretty simple solution - the user just can declare the files in XML configuration tag in the appropriate order, like
```
<configuration>
    <includes>
          <!--1.  here comes the first file with least priority-->
          <!--2.  here comes another file with higher precedence -->
    </includes>
</configuration>
```

Can you please explain what do you mean?

P.S: I have removed `invalid` label, since `invalid` label is for issues that are not valid in it's essence. It is not yet clear to me that this is the case

**Comment by temalead** [comment] 2023-05-10 20:33
@Mikhail2048, If I'm not mistaken, client can write several files in config 
Suppose, file1 and file2 have same property - _abc_.
In file1: _abc_=new-value
In file2: _abc_=old-value

Suppose, plugin reads file2 last with old-value of property. 
Client expects to recieve new value but get old-value. Of course, we can write in docs that last file has higher precedence than file1 but client may not read the documentation or just forget about this condition

Maybe it`s not good behaviour? Please correct me if I'm wrong and close issue. Thanks!

**Comment by mipo256** [comment] 2023-05-11 12:17
I think I understood your point

The problem is - in case of multiple properties declarations, you still need to take over the other, that inevitable. Either it will be in `file1` or `file2`. I guess it is a perfect place to be stated in the docs that the files, specified in `<includes>` element are expected to be in the increasing precedence. Like properties from `file2` in case of conflict is favored over properties in `file1` 

How do you think it should be resolved? I do not see any other option that makes sense to me

**Comment by temalead** [comment] 2023-05-11 17:50
@Mikhail2048, fine, i like your decision :)
But maybe at least we can print log with WARN level in io.polivakha.mojo.properties.ReadPropertiesMojo#loadProperties like this using apache-commons, for example:

```
List<String> resourceProperties = IOUtils.readLines(inputStream, "UTF-8");
Set<String> newPropertyKeys = resourceProperties.stream()
                .map(line -> {
                    String[] keyValueProperty = line.split("=");
                    Assert.isTrue(keyValueProperty.length > 0,"Error");
                    
                    return keyValueProperty[0];
                })
                .collect(Collectors.toSet());

existedProperties.forEach(existedProperty -> {
            if (newPropertyKeys.contains(existedProperty)) {
                log.warn("Property {} already defined in scope. Overriding", existedProperty);
            }
        });
```

We can make do with your decision alone and not log this because of course my solution decrease performance

**Comment by mipo256** [comment] 2023-05-12 05:48
Ok, fine)

You can create a PR to log out the properties that present in different files, issue a log or smth like that, that will not be redundant, that's for sure. However the properties search and population logic is not needed, it is already implemented)

**Comment by temalead** [comment] 2023-05-12 07:14
Thanks for understanding! 
I create PR after you merge your changes from GH-2 branch

**Comment by mipo256** [comment] 2023-05-12 07:18
Ok, feel free to publish your PR, do not wait, I will take a look)

**Closed as completed** 2023-05-13 07:38 UTC
